server:
  url: "http://localhost:8080/geoserver"
  verifytls: true

credentials:
  user: "admin"
  pass: "geoserver"

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

db:
  pg_host:
    docker: "geodatabase"
    local: "localhost"
  pg_port:
    docker: 5432
    local: 6432
  pg_db: "acceptance"
  pg_user: "geoserver"
  pg_password: "geoserver"
  pg_schema: "test1"
